# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63d6bd3fd1e3dcff1c3162a70b97495f770039f188adba65a07ef852230a29c302268caa6a50ca535f7934ca813603ec5b799cfb92a9d20f680f409f76aeffad

test:
  secret_key_base: bbdf2f8aa5bacb2821f902d5c8cf5bbd86f63c1203aa2e2c9b279a54a1e508466ea605f0fc65a13aa44ec8070329c0a41bd5f81442ac2d65ecc2bc734769fb63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
